//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoMonitores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asesoria
    {
        public int idAsesoria { get; set; }
        public Nullable<int> idMonitor { get; set; }
        public Nullable<int> idCurso { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string aula { get; set; }
    
        public virtual Curso Curso { get; set; }
        public virtual Monitor Monitor { get; set; }
    }
}
